[package]
description = "AdventOfCode."
version = "1.0.0"
name = "adventofcode-rs"
authors = ["Lokananda", "Fnu Lnu <no-reply@rust-lang.org>"]

[[bin]]
path = "day1.rs"
name = "day1"
test = false
bench = false